config/routes.rb
Rails.application.routes.draw do
  get '/hearo/panel' => 'hearos#panel', as: 'hearo_panel'
  get '/smyler/panel' => 'smylers#panel', as: 'smyler_panel'
  get '/hearos/verify' => 'hearos#verify', as: 'verify_hearo'

  get '/hearos/max-meetings' => 'hearos#max_meetings'

  resources :hearos do
      resources :bookings, only: [:show] do
        resources :meetings, only: [:create]
      end
  end

  resources :hearos do
    resources :reviews, only: [:new, :create, :index]
  end

  resources :reviews
  resources :meetings
  resources :bookings
  resources :smylers
  resources :sessions
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  # Routes for Google authentication

  root to: 'welcome#home'
  get '/login' => 'smylers#new'
  get '/logout' => 'sessions#destroy', as: 'logout'
  get '/smyler/signup' => 'smylers#new'

  #facebook oauth2 routes
  get '/auth/:provider/callback' => 'smylers#create'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :hearo

end

app/models/gender.rb
class Gender < ApplicationRecord
  has_many :smylers
  has_many :hearos

  validates :name, uniqueness: true
end

app/models/hearo.rb
class Hearo < ApplicationRecord
  has_many :reviews
  has_many :bookings
  belongs_to :status
  has_many :meetings
  belongs_to :gender
  belongs_to :specialty
  has_many :smylers, through: :meetings
  has_secure_password

  validates :username, uniqueness: true
  validates :email, uniqueness: true

  scope :verified, -> { where(verified: true) }
  scope :most_meetings, -> { where(id: Meeting.maximum(:hearo_id)).first }

  def specialty_attributes=(attributes)
    self.specialty = Specialty.find_or_create_by(name: attributes[:name])
  end

  def full_name
    if self.middle_name
      self.first_name + ' ' + self.middle_name + ' ' + self.last_name
    else
      self.first_name + ' ' + self.last_name
    end
  end

  def self.online
    self.all.select {|h| h.status.name == 'Online'}
  end

  def self.specialty_order
    self.all.sort_by {|hearo| hearo.specialty.id}
  end
end

app/models/meeting.rb
class Meeting < ApplicationRecord
  belongs_to :smyler
  belongs_to :hearo

end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :smyler
  belongs_to :hearo
end

app/models/smyler.rb
class Smyler < ApplicationRecord
  has_many :reviews
  has_many :meetings
  has_many :hearos, through: :meetings
  has_one :gender
  has_secure_password

  validates :username, uniqueness: true
  validates :email, uniqueness: true
end

app/models/specialty.rb
class Specialty < ApplicationRecord
  has_many :hearos

  validates :name, uniqueness: true
end

app/models/status.rb
class Status < ApplicationRecord
  has_many :hearos
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController

  def create
    @booking = Booking.new(booking_params)
    @booking.hearo = current_hearo
    if @booking.save
      return redirect_to hearo_panel_path
    end
  end

  def destroy
    Booking.find_by(id: params[:id]).destroy
    return redirect_to hearo_panel_path
  end

  private

  def booking_params
    params.require(:booking).permit(:starts_at, :hearo_id)
  end
end

app/controllers/hearos_controller.rb
class HearosController < ApplicationController

  def index
    #TODO
    redirect_home
  end

  def show
    redirect_home if !smyler_logged_in?
    if @hearo = Hearo.find_by(id: params[:id])
      @meeting = Meeting.new
    else
      redirect_home #helper method defined in application_controller.rb
    end
  end

  def panel
    redirect_home if !hearo_logged_in?
    @hearo = current_hearo
    if !@hearo.verified
      return redirect_to verify_hearo_path
    end
    @booking = @hearo.bookings.build
  end

  def new
    redirect_home if hearo_logged_in?
    @hearo = current_hearo
    @hearo.build_specialty
  end

  def create
    @hearo = Hearo.new(hearo_params)
    if @hearo.save
      session['hearo_id'] = @hearo.id
      redirect_to verify_hearo_path
    else
      render :new
    end
  end

  def edit
    redirect_home if !hearo_logged_in?
    @hero = current_hearo
  end

  def update
    redirect_home if !hearo_logged_in?
    @hearo = current_hearo
    if @hearo.update (hearo_params)
      return redirect_to hearo_panel_path
    end
    render :edit
  end

  def verify
    redirect_home if !hearo_logged_in?
    @hearo = current_hearo
  end

  def max_meetings
    @hearo = Hearo.most_meetings
  end

  private

  def hearo_params
    params.require(:hearo).permit(:gender_id, :username, :email, :password, :password_confirmation, :first_name, :last_name, :middle_name, :specialty, :dob, :status_id, :therapist_code, specialty_attributes: [:name])
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  #Only for Cohort project purposes
  def index
    @hearo = Hearo.find_by(id: params[:hearo_id])
  end

  def new
    @hearo = Hearo.find_by(id: params[:hearo_id])
    @review = @hearo.reviews.build
  end

  def create
    @review = Review.new(review_params)
    @review.smyler = current_smyler
    @review.hearo_id = params[:hearo_id]
    if @review.save
      redirect_to hearo_reviews_path(@review.hearo)
    else
      render :new
    end
  end

  private

  def review_params
    params.require(:review).permit(:score, :content)
  end
end

app/controllers/smylers_controller.rb
class SmylersController < ApplicationController
  def show
    @smyler = current_smyler
  end

  def panel
    redirect_home if !smyler_logged_in?
    @smyler = current_smyler
  end

  def new
    redirect_home if smyler_logged_in?
    @smyler = current_smyler
  end

  def create
    if auth
      @smyler = Smyler.find_or_create_by(uid: auth['uid']) do |u|
        u.first_name = auth['info']['name']
        u.email = auth['info']['email']
        u.image = auth['info']['image']
        u.password = "FACEBOOK"  #TODO Find a secure method to use bcrypt in this case
      end
      session[:smyler_id] = @smyler.id
      redirect_to smyler_panel_path
    else
      @smyler = Smyler.new(smyler_params)
      if @smyler.save
        session['smyler_id'] = @smyler.id
        redirect_to smyler_panel_path
      else
        render :new
      end
    end
  end

  def edit
    redirect_home if !smyler_logged_in?
    @smyler = current_smyler
  end

  def update
    @smyler = current_smyler
    if @smyler.update (smyler_params)
      return redirect_to smyler_panel_path
    end
    render :edit
  end

  private
 
  def auth
    request.env['omniauth.auth']
  end

  def smyler_params
    params.require(:smyler).permit(:gender_id, :username, :email, :password, :password_confirmation, :first_name, :last_name, :middle_name, :dob)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def home
    @smyler = current_smyler
    @hearo = current_hearo
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def dynamic_route_to_home_string
    if smyler_logged_in?
      smyler_panel_path
    elsif hearo_logged_in?
      hearo_panel_path
    else
      '/'
    end
  end
end

app/helpers/bookings_helper.rb
module BookingsHelper
end

app/helpers/hearos_helper.rb
module HearosHelper
end

app/helpers/meetings_helper.rb
module MeetingsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/smylers_helper.rb
module SmylersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/reviews/index.html.erb
<div class="centered jumbotron">
  <h1 class="display-4">Reviews for <%= @hearo.full_name %></h1>
  <hr class="my-3">
    <div class="col bg-light">
    <p class=lead>Reviews:</p>
    <ul class="list-group list-group-flush">
      <% @hearo.reviews.each do |review|%>
        <li class="list-group-item">
          <p>Score: <%= review.score %></p>
          <p>Note: <%= review.content %></p>
        </li>
      <% end %>
    </ul>
  </div>

</div>

app/views/reviews/new.html.erb
<div class="centered jumbotron">
  <h1 class="display-4">New Review for Hearo <%= @hearo.full_name %></h1>

<% if @review.errors.any? %>
    <div id="error_explanation">
        <h2><%= pluralize(@review.errors.count, "error") %> prohibited this @review from being saved:</h2>

        <ul>
        <% @review.errors.full_messages.each do |message| %>
            <li><%= message %></li>
        <% end %>
        </ul>
    </div>
<% end %>

<div class='row'>
    <div class='col'>
        <%= form_with(model: @review, url: hearo_reviews_path(@hearo))  do |form| %>


        <div class="field form-group row">
            <%= form.label 'Score:', class: "col-sm-2 col-form-label" %>
            <div class="col-sm-10">
                <%= form.text_field :score, class: "form-control" %>
            </div>
        </div>

        <div class="field form-group row">
            <%= form.label "Notes:", class: "col-sm-2 col-form-label" %>
            <div class="col-sm-10">
                <%= form.text_area :content, class: "form-control" %>
            </div>
        </div>

        
          <div class="actions form-group">
              <div>
              <%= form.submit "Submit Review", class: "btn btn-primary btn-lg" %>
              </div>
          </div>

        </div>
    </div>

<% end %>

</div>

app/views/welcome/home.html.erb
<div class="centered jumbotron jumbotron-fluid">
  <%= image_tag '/assets/smyle-logo-horizontal.png', class: "img-fluid" %>
  <p class="lead">Smyle is a community of certified therapists called Hearos that can help you bring back your SmYle to Lyfe!</p>
  <hr class="my-3">
  <%= link_to 'Start SmYling!', new_smyler_path, class: "btn btn-primary btn-lg" %>
  <%= link_to 'Become a Hearo!', new_hearo_path, class: "btn btn-primary btn-lg" %>
  <hr class="my-3">
  <p class="lead">How it works:</p>
  <p class="lead">Once you become a SmYler you will be able to set meetings with hearos which are certified therapists and will make the most to put back a SmYle on your face. <span>Signup</span> now and start SmYling!</p>
  <div>
    <p class='text-primary'>Verified Hearos: <%= Hearo.verified.count %></p>
  </div>

 
</div>