config/routes.rb
Rails.application.routes.draw do
  get '/hearo/panel' => 'hearos#panel', as: 'hearo_panel'
  get '/smyler/panel' => 'smylers#panel', as: 'smyler_panel'
  get '/hearos/verify' => 'hearos#verify', as: 'verify_hearo'

  get '/hearos/max-meetings' => 'hearos#max_meetings'

  resources :hearos do
      resources :bookings, only: [:show] do
        resources :meetings, only: [:create]
      end
  end

  resources :hearos do
    resources :reviews, only: [:new, :create, :index]
  end

  resources :reviews
  resources :meetings
  resources :bookings
  resources :smylers
  resources :sessions
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  # Routes for Google authentication

  root to: 'welcome#home'
  get '/login' => 'smylers#new'
  get '/logout' => 'sessions#destroy', as: 'logout'
  get '/smyler/signup' => 'smylers#new'

  #facebook oauth2 routes
  get '/auth/:provider/callback' => 'smylers#create'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :hearo

end

app/models/gender.rb
class Gender < ApplicationRecord
  has_many :smylers
  has_many :hearos

  validates :name, uniqueness: true
end

app/models/hearo.rb
class Hearo < ApplicationRecord
  has_many :reviews
  has_many :bookings
  belongs_to :status
  has_many :meetings
  belongs_to :gender
  belongs_to :specialty
  has_many :smylers, through: :meetings
  has_secure_password

  validates :username, uniqueness: true
  validates :email, uniqueness: true

  scope :verified, -> { where(verified: true) }
  scope :most_meetings, -> { where(id: Meeting.maximum(:hearo_id)).first }

  def specialty_attributes=(attributes)
    self.specialty = Specialty.find_or_create_by(name: attributes[:name])
  end

  def full_name
    if self.middle_name
      self.first_name + ' ' + self.middle_name + ' ' + self.last_name
    else
      self.first_name + ' ' + self.last_name
    end
  end

  def self.online
    self.all.select {|h| h.status.name == 'Online'}
  end

  def self.specialty_order
    self.all.sort_by {|hearo| hearo.specialty.id}
  end
end

app/models/meeting.rb
class Meeting < ApplicationRecord
  belongs_to :smyler
  belongs_to :hearo

end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :smyler
  belongs_to :hearo
end

app/models/smyler.rb
class Smyler < ApplicationRecord
  has_many :reviews
  has_many :meetings
  has_many :hearos, through: :meetings
  has_one :gender
  has_secure_password

  validates :username, uniqueness: true
  validates :email, uniqueness: true
end

app/models/specialty.rb
class Specialty < ApplicationRecord
  has_many :hearos

  validates :name, uniqueness: true
end

app/models/status.rb
class Status < ApplicationRecord
  has_many :hearos
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController

  def create
    @booking = Booking.new(booking_params)
    @booking.hearo = current_hearo
    if @booking.save
      return redirect_to hearo_panel_path
    end
  end

  def destroy
    Booking.find_by(id: params[:id]).destroy
    return redirect_to hearo_panel_path
  end

  private

  def booking_params
    params.require(:booking).permit(:starts_at, :hearo_id)
  end
end

app/controllers/hearos_controller.rb
class HearosController < ApplicationController

  def index
    #TODO
    redirect_home
  end

  def show
    redirect_home if !smyler_logged_in?
    if @hearo = Hearo.find_by(id: params[:id])
      @meeting = Meeting.new
    else
      redirect_home #helper method defined in application_controller.rb
    end
  end

  def panel
    redirect_home if !hearo_logged_in?
    @hearo = current_hearo
    if !@hearo.verified
      return redirect_to verify_hearo_path
    end
    @booking = @hearo.bookings.build
  end

  def new
    redirect_home if hearo_logged_in?
    @hearo = current_hearo
    @hearo.build_specialty
  end

  def create
    @hearo = Hearo.new(hearo_params)
    if @hearo.save
      session['hearo_id'] = @hearo.id
      redirect_to verify_hearo_path
    else
      render :new
    end
  end

  def edit
    redirect_home if !hearo_logged_in?
    @hero = current_hearo
  end

  def update
    redirect_home if !hearo_logged_in?
    @hearo = current_hearo
    if @hearo.update (hearo_params)
      return redirect_to hearo_panel_path
    end
    render :edit
  end

  def verify
    redirect_home if !hearo_logged_in?
    @hearo = current_hearo
  end

  def max_meetings
    @hearo = Hearo.most_meetings
  end

  private

  def hearo_params
    params.require(:hearo).permit(:gender_id, :username, :email, :password, :password_confirmation, :first_name, :last_name, :middle_name, :specialty, :dob, :status_id, :therapist_code, specialty_attributes: [:name])
  end
end

app/controllers/meetings_controller.rb
class MeetingsController < ApplicationController

  def index
    if smyler_logged_in?
      @meetings = current_smyler.meetings
    elsif hearo_logged_in?
      @meetings = current_hearo.meetings
    else
      return redirect_to '/'
    end
  end

  def show
    return redirect_home if !logged_in?
    @meeting = Meeting.find_by(id: params[:id])
  end

  def create
    @meeting = Meeting.new(meeting_params)
    @meeting.smyler = current_smyler
    @meeting.hearo_id = params[:hearo_id]
    if @meeting.save
      Booking.destroy(params[:booking_id])
      redirect_home
    else
      render :new
    end
  end

  def destroy
    meeting = Meeting.find_by(id: params[:id])
    hearo = meeting.hearo
    booking = Booking.new(hearo_id: hearo.id, starts_at: meeting.start_time)
    if booking.save
      meeting.destroy
      return redirect_home
    end
  end

  private

  def meeting_params
    params.require(:meeting).permit(:start_time, :title, :notes, :hearo_id, :smyler_id)
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  #Only for Cohort project purposes
  def index
    @hearo = Hearo.find_by(id: params[:hearo_id])
  end

  def new
    @hearo = Hearo.find_by(id: params[:hearo_id])
    @review = @hearo.reviews.build
  end

  def create
    @review = Review.new(review_params)
    @review.smyler = current_smyler
    @review.hearo_id = params[:hearo_id]
    if @review.save
      redirect_to hearo_reviews_path(@review.hearo)
    else
      render :new
    end
  end

  private

  def review_params
    params.require(:review).permit(:score, :content)
  end
end

app/controllers/smylers_controller.rb
class SmylersController < ApplicationController
  def show
    @smyler = current_smyler
  end

  def panel
    redirect_home if !smyler_logged_in?
    @smyler = current_smyler
  end

  def new
    redirect_home if smyler_logged_in?
    @smyler = current_smyler
  end

  def create
    if auth
      @smyler = Smyler.find_or_create_by(uid: auth['uid']) do |u|
        u.first_name = auth['info']['name']
        u.email = auth['info']['email']
        u.image = auth['info']['image']
        u.password = "FACEBOOK"  #TODO Find a secure method to use bcrypt in this case
      end
      session[:smyler_id] = @smyler.id
      redirect_to smyler_panel_path
    else
      @smyler = Smyler.new(smyler_params)
      if @smyler.save
        session['smyler_id'] = @smyler.id
        redirect_to smyler_panel_path
      else
        render :new
      end
    end
  end

  def edit
    redirect_home if !smyler_logged_in?
    @smyler = current_smyler
  end

  def update
    @smyler = current_smyler
    if @smyler.update (smyler_params)
      return redirect_to smyler_panel_path
    end
    render :edit
  end

  private
 
  def auth
    request.env['omniauth.auth']
  end

  def smyler_params
    params.require(:smyler).permit(:gender_id, :username, :email, :password, :password_confirmation, :first_name, :last_name, :middle_name, :dob)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def home
    @smyler = current_smyler
    @hearo = current_hearo
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def dynamic_route_to_home_string
    if smyler_logged_in?
      smyler_panel_path
    elsif hearo_logged_in?
      hearo_panel_path
    else
      '/'
    end
  end
end

app/helpers/bookings_helper.rb
module BookingsHelper
end

app/helpers/hearos_helper.rb
module HearosHelper
end

app/helpers/meetings_helper.rb
module MeetingsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/smylers_helper.rb
module SmylersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/hearos/_form.html.erb
<% if hearo.errors.any? %>
    <div id="error_explanation">
        <h2><%= pluralize(hearo.errors.count, "error") %> prohibited this hearo from being saved:</h2>

        <ul>
        <% hearo.errors.full_messages.each do |message| %>
            <li><%= message %></li>
        <% end %>
        </ul>
    </div>
<% end %>

<div class='row'>
    <div class='col'>
        <%= form_with(model: hearo, local: true) do |form| %>

        <% if !hearo.id %>
        <div class="field form-group row">
            <%= form.label :username, class: "col-sm-2 col-form-label" %>
            <div class="col-sm-10">
                <%= form.text_field :username, class: "form-control" %>
            </div>
        </div>
        <% end%>

        <div class="field form-group row">
            <%= form.label :email, class: "col-sm-2 col-form-label" %>
            <div class="col-sm-10">
                <%= form.text_field :email, class: "form-control" %>
            </div>
        </div>

        <div class="field form-group row">
            <%= form.label :password, class: "col-sm-2 col-form-label" %>
            <div class="col-sm-10">
                <%= form.password_field :password, class: "form-control" %>
            </div>
        </div>

        <div class="field form-group row">
            <%= form.label :first_name, class: "col-sm-2 col-form-label" %>
            <div class="col-sm-10">
                <%= form.text_field :first_name, class: "form-control" %>
            </div>
        </div>

        <div class="field form-group row">
            <%= form.label :last_name, class: "col-sm-2 col-form-label" %>
            <div class="col-sm-10">
                <%= form.text_field :last_name, class: "form-control" %>
            </div>
        </div>

        <%= form.fields_for :specialty do |s| %>
        <div class="field form-group row">
            <%= s.label :specialty, class: "col-sm-2 col-form-label" %>
            <div class="col-sm-10">
                <%= s.text_field :name, list: "specialty_autocomplete", class: "form-control" %>
                <datalist id="specialty_autocomplete">
                    <% Specialty.all.each do |specialty| %>
                        <option value="<%= specialty.name %>">
                    <% end %>
                </datalist>
            </div>
        </div>
        <% end %>

        <div class="field form-group row">
            <%= form.label :gender, class: "col-sm-2 col-form-label" %>
            <div class="col-sm-10">
                <%= form.collection_select :gender_id, Gender.all, :id, :name, {class: "form-control"} %>  <!--- TODO: Find a way to add class for boostrap -->
            </div>
        </div>

        <div class="field form-group row">
            <%= form.label :therapist_code, class: "col-sm-2 col-form-label" %>
            <div class="col-sm-10">
                <%= form.text_field :therapist_code, class: "form-control" %>
            </div>
        </div>

        <div class="field form-group row">
            <%= form.label "Date of Birth", class: "col-sm-2 col-form-label" %>
            <div class="col-sm-10">
                <%= form.date_field :dob, class: "form-control" %>
            </div>
        </div>

        <% if !@hearo.id %>
          <div class="actions form-group">
              <div>
              <%= form.submit "Request Verification!", class: "btn btn-primary btn-lg" %>
              </div>
          </div>
        <% else %>
          <div class="actions form-group">
              <div>
              <%= form.submit "Submit Changes", class: "btn btn-primary btn-lg" %>
              </div>
          </div>
        <% end%>

        </div>
    </div>

<% end %>

app/views/hearos/confirmation.html.erb
<h1>Hello Hearo <%= @hearo.first_name %></h1>
<p>Please wait to ve verified... It may take up to 50 years. Thanks!</p>

app/views/hearos/edit.html.erb
<div class="jumbotron">
    <h1 class="display-4">Edit Your Profile</h1>

  <%= render 'form', hearo: @hearo %>
    
</div>

app/views/hearos/max_meetings.html.erb
<%= content_tag(:h1, @hearo.full_name) %>

app/views/hearos/new.html.erb
<div class="centered jumbotron">
  <h1 class="display-4">Signup Hearo!</h1>

  <%= render 'form', hearo: @hearo %>

</div>

app/views/hearos/panel.html.erb
<div class="jumbotron">
    <h1 class="display-4 centered">Hello Hearo <%= link_to @hearo.first_name, edit_hearo_path(@hearo) if @hearo.verified%></h1>
    <hr class="my-3">
    <div class="status centered">
      <p class="lead">Your current status is set to: <span><%= @hearo.status.name %></span>
        <%= form_with model: @hearo do |f|%>
                <%= f.collection_select :status_id, Status.all, :id, :name, {class: "form-control"} %>
                <%= f.submit "✔️" %>  <!--- TODO: Find a way to add class for boostrap -->
        <% end %>
      </p>
    </div>
    <hr class="my-3">

    <div class="row">

        <div class="col bg-light">
          <p class=lead>Reserve Weekly Meeting Times:</p>
          <%= form_with(model: @booking) do |f|%>
            <%= f.label "Date and Time:" %>
            <%= f.datetime_field :starts_at %>
            <%= f.submit "Create" %>
          <% end %>
        </div>

        <div class="col bg-light">
          <p class=lead><%= link_to 'Booked Meetings:', meetings_path %></p>
          <ul class="list-group list-group-flush">
            <% @hearo.meetings.each do |meeting|%>
              <li class="list-group-item">
               <%= link_to meeting.start_time, meeting_path(meeting) %>
              </li>
            <% end %>
        </ul>
        </div>
    </div>

    <div class="row">
        <div class="col bg-light">
        <p class=lead>Bookings:</p>
        <ul class="list-group list-group-flush">
            <% @hearo.bookings.each do |booking|%>
              <% if booking.id %>
              <li class="list-group-item">
               <%= form_tag booking_path(booking), method: "delete" do %>
                 <%= booking.starts_at %>  <%= submit_tag "X" %>
               <% end %>
              </li>
              <% end %>
            <% end %>
        </ul>
        </div>

        <div class="col bg-light">
          <p class=lead>Requests:</p>
        </div>
    </div>
    <div class="centered pad container">
    </div>
</div>

app/views/hearos/show.html.erb
<div class='jumbotron'>

  <div class="col bg-light">
    <p class='lead'>Hearo <%= @hearo.full_name %></p>
    <ul class="list-group list-group-flush">
      <li class="list-group-item">
         Username: <%= @hearo.username %>
      </li>
      <li class="list-group-item">
         First Name: <%= @hearo.first_name %>
      </li>
      <li class="list-group-item">
         Last Name: <%= @hearo.last_name %>
      </li>
      <li class="list-group-item">
         Specialty: <%= @hearo.specialty.name %>
      </li>
       <li class="list-group-item">
         Gender: <%= @hearo.gender.name %>
      </li>
      <li class="list-group-item">
         <%= link_to 'Make a review!', new_hearo_review_path(@hearo) %>
      </li>
    </ul>
  </div>
  
  <hr class="my-3">

  <div class="col bg-light">
    <p class='lead'>Available Times:</p>
        <% if @hearo.bookings.empty? %>
            <ul class="list-group list-group-flush">
                <li class="list-group-item">
                  <p> There are no available times at the moment!</p>
                </li>
        <% else %>
                <% @hearo.bookings.each do |booking|%>
                <li class="list-group-item">
                <%= form_for [@hearo, booking, @meeting] do |f|%>
                    <%= f.text_field :start_time, type: 'hidden', value: booking.starts_at %>
                    <%= booking.starts_at %>  <%= submit_tag "Book" %>
                <% end %>
                </li>
                <% end %>
            </ul>
        <% end %>
  </div>

</div>

app/views/hearos/verify.html.erb
<div class="centered jumbotron">
  <h1 class="display-4">Hello Hearo <%= @hearo.first_name %></h1>
  <p class="lead">Please wait to ve verified... It may take up to 50 years. Thanks!</p>
  <p class="lead">You will be notified by email.</p>
  <div class="progress">
    <div class="progress-bar progress-bar-striped progress-bar-animated" role="progressbar" aria-valuenow="75" aria-valuemin="0" aria-valuemax="100" style="width: 75%"></div>
  </div>
</div>

app/views/meetings/index.html.erb
<div class='jumbotron'>

  <div class="col bg-light">
    <p class=lead>Meetings:</p>
    <ul class="list-group list-group-flush">
      <% @meetings.each do |meeting|%>
        <% if meeting.id %>
        <li class="list-group-item">
         <%= link_to meeting.title || meeting.start_time, meeting_path(meeting) %> on: <%= meeting.start_time %> with: <%= hearo_logged_in? ? meeting.smyler.username : meeting.hearo.username %>
        </li>
        <% end %>
      <% end %>
    </ul>
  </div>

</div>

app/views/meetings/new.html.erb
<h1>This is where meetings can be created</h1>

app/views/meetings/show.html.erb
<div class='jumbotron'>
    <p class="lead">Smyler: <%= @meeting.smyler.username %></p>
    <p class="lead">Hearo: <%= @meeting.hearo.username %></p>
    <p class="lead">Title: <%= @meeting.title %></p>
    <p class="lead">On: <%= @meeting.start_time %></p>
    <p class="lead">Notes: <%= @meeting.notes %></p>
    <%= form_with model: @meeting, method: 'delete' do |f| %>
      <%= f.submit 'Cancel Meeting' %>
    <% end %>

</div>

app/views/smylers/_form.html.erb
<% if smyler.errors.any? %>
    <div id="error_explanation">
        <h2><%= pluralize(smyler.errors.count, "error") %> prohibited this smyler from being saved:</h2>

        <ul>
        <% smyler.errors.full_messages.each do |message| %>
            <li><%= message %></li>
        <% end %>
        </ul>
    </div>
<% end %>

<div class='row'>
    <div class='col'>
        <%= form_with(model: smyler, local: true) do |form| %>

        <% if !smyler.id %>
        <div class="field form-group row">
            <%= form.label :username, class: "col-sm-2 col-form-label" %>
            <div class="col-sm-10">
                <%= form.text_field :username, class: "form-control" %>
            </div>
        </div>
        <% end%>

        <div class="field form-group row">
            <%= form.label :email, class: "col-sm-2 col-form-label" %>
            <div class="col-sm-10">
                <%= form.text_field :email, class: "form-control" %>
            </div>
        </div>

        <div class="field form-group row">
            <%= form.label :password, class: "col-sm-2 col-form-label" %>
            <div class="col-sm-10">
                <%= form.password_field :password, class: "form-control" %>
            </div>
        </div>

        <div class="field form-group row">
            <%= form.label :first_name, class: "col-sm-2 col-form-label" %>
            <div class="col-sm-10">
                <%= form.text_field :first_name, class: "form-control" %>
            </div>
        </div>

        <div class="field form-group row">
            <%= form.label :last_name, class: "col-sm-2 col-form-label" %>
            <div class="col-sm-10">
                <%= form.text_field :last_name, class: "form-control" %>
            </div>
        </div>

        <div class="field form-group row">
            <%= form.label :gender, class: "col-sm-2 col-form-label" %>
            <div class="col-sm-10">
                <%= form.collection_select :gender_id, Gender.all, :id, :name, {class: "form-control"} %>  <!--- TODO: Find a way to add class for boostrap -->
            </div>
        </div>

        <div class="field form-group row">
            <%= form.label "Date of Birth", class: "col-sm-2 col-form-label" %>
            <div class="col-sm-10">
                <%= form.date_field :dob, class: "form-control" %>
            </div>
        </div>

        <% if !@smyler.id %>
          <div class="actions form-group">
              <div>
              <%= form.submit "Start Smyling!", class: "btn btn-primary btn-lg" %>
              </div>
          </div>
        <% else %>
          <div class="actions form-group">
              <div>
              <%= form.submit "Submit Changes", class: "btn btn-primary btn-lg" %>
              </div>
          </div>
        <% end%>

        </div>
    </div>

<% end %>

app/views/smylers/edit.html.erb
<div class="jumbotron">
    <h1 class="display-4">Edit Your Profile</h1>

  <%= render 'form', smyler: @smyler %>
    
</div>

app/views/smylers/new.html.erb
<div class="centered jumbotron">
  <h1 class="display-4">Become a Smyler!!</h1>

  <%= render 'form', smyler: @smyler %>

<p>Or Signup with Facebook!</p>
<%= link_to 'Facebook Signup', '/auth/facebook' %>
</div>

app/views/smylers/panel.html.erb
<div class="jumbotron">
    <h1 class="display-4 centered">Hello Smyler <%= link_to @smyler.first_name, edit_smyler_path(@smyler)%></h1>
    <hr class="my-3">

    <div class="row">

        <div class="col bg-light">
          <p class=lead>Online Hearos:</p>
          <ul class="list-group list-group-flush">
            <% Hearo.online.each do |hearo|%>
              <% if hearo.id %>
              <li class="list-group-item">
               <%= link_to hearo.username, hearo_path(hearo) %>
              </li>
              <% end %>
            <% end %>
        </ul>
        </div>

        <div class="col bg-light">
          <p class=lead><%= link_to 'Booked Meetings:', meetings_path %></p>
          <ul class="list-group list-group-flush">
            <% @smyler.meetings.each do |meeting|%>
              <li class="list-group-item">
               <%= link_to meeting.start_time, meeting_path(meeting) %>
              </li>
            <% end %>
        </ul>
        </div>
    </div>

    <div class="row">
        <div class="col bg-light">
        <p class=lead>Hearo by Specialty:</p>
        <ul class="list-group list-group-flush">
            <% Hearo.specialty_order.each do |hearo|%>
              <% if hearo.id %>
              <li class="list-group-item">
               <p>
                 <%= link_to hearo.full_name, hearo_path(hearo) %> - <%= hearo.specialty.name %>
               </p>
              </li>
              <% end %>
            <% end %>
        </ul>
        </div>

    </div>
    <div class="centered pad container">
     <p class=lead></p>
    </div>
</div>