config/routes.rb
Rails.application.routes.draw do
  get '/hearo/panel' => 'hearos#panel', as: 'hearo_panel'
  get '/smyler/panel' => 'smylers#panel', as: 'smyler_panel'
  get '/hearos/verify' => 'hearos#verify', as: 'verify_hearo'

  get '/hearos/max-meetings' => 'hearos#max_meetings'

  resources :hearos do
      resources :bookings, only: [:show] do
        resources :meetings, only: [:create]
      end
  end

  resources :hearos do
    resources :reviews, only: [:new, :create, :index]
  end

  resources :reviews
  resources :meetings
  resources :bookings
  resources :smylers
  resources :sessions
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  # Routes for Google authentication

  root to: 'welcome#home'
  get '/login' => 'smylers#new'
  get '/logout' => 'sessions#destroy', as: 'logout'
  get '/smyler/signup' => 'smylers#new'

  #facebook oauth2 routes
  get '/auth/:provider/callback' => 'smylers#create'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :hearo

end

app/models/gender.rb
class Gender < ApplicationRecord
  has_many :smylers
  has_many :hearos

  validates :name, uniqueness: true
end

app/models/hearo.rb
class Hearo < ApplicationRecord
  has_many :reviews
  has_many :bookings
  belongs_to :status
  has_many :meetings
  belongs_to :gender
  belongs_to :specialty
  has_many :smylers, through: :meetings
  has_secure_password

  validates :username, uniqueness: true
  validates :email, uniqueness: true

  scope :verified, -> { where(verified: true) }
  scope :most_meetings, -> { where(id: Meeting.maximum(:hearo_id)).first }

  def specialty_attributes=(attributes)
    self.specialty = Specialty.find_or_create_by(name: attributes[:name])
  end

  def full_name
    if self.middle_name
      self.first_name + ' ' + self.middle_name + ' ' + self.last_name
    else
      self.first_name + ' ' + self.last_name
    end
  end

  def self.online
    self.all.select {|h| h.status.name == 'Online'}
  end

  def self.specialty_order
    self.all.sort_by {|hearo| hearo.specialty.id}
  end
end

app/models/meeting.rb
class Meeting < ApplicationRecord
  belongs_to :smyler
  belongs_to :hearo

end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :smyler
  belongs_to :hearo
end

app/models/smyler.rb
class Smyler < ApplicationRecord
  has_many :reviews
  has_many :meetings
  has_many :hearos, through: :meetings
  has_one :gender
  has_secure_password

  validates :username, uniqueness: true
  validates :email, uniqueness: true
end

app/models/specialty.rb
class Specialty < ApplicationRecord
  has_many :hearos

  validates :name, uniqueness: true
end

app/models/status.rb
class Status < ApplicationRecord
  has_many :hearos
end

app/controllers/hearos_controller.rb
class HearosController < ApplicationController

  def index
    #TODO
    redirect_home
  end

  def show
    redirect_home if !smyler_logged_in?
    if @hearo = Hearo.find_by(id: params[:id])
      @meeting = Meeting.new
    else
      redirect_home #helper method defined in application_controller.rb
    end
  end

  def panel
    redirect_home if !hearo_logged_in?
    @hearo = current_hearo
    if !@hearo.verified
      return redirect_to verify_hearo_path
    end
    @booking = @hearo.bookings.build
  end

  def new
    redirect_home if hearo_logged_in?
    @hearo = current_hearo
    @hearo.build_specialty
  end

  def create
    @hearo = Hearo.new(hearo_params)
    if @hearo.save
      session['hearo_id'] = @hearo.id
      redirect_to verify_hearo_path
    else
      render :new
    end
  end

  def edit
    redirect_home if !hearo_logged_in?
    @hero = current_hearo
  end

  def update
    redirect_home if !hearo_logged_in?
    @hearo = current_hearo
    if @hearo.update (hearo_params)
      return redirect_to hearo_panel_path
    end
    render :edit
  end

  def verify
    redirect_home if !hearo_logged_in?
    @hearo = current_hearo
  end

  def max_meetings
    @hearo = Hearo.most_meetings
  end

  private

  def hearo_params
    params.require(:hearo).permit(:gender_id, :username, :email, :password, :password_confirmation, :first_name, :last_name, :middle_name, :specialty, :dob, :status_id, :therapist_code, specialty_attributes: [:name])
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  #Only for Cohort project purposes
  def index
    @hearo = Hearo.find_by(id: params[:hearo_id])
  end

  def new
    @hearo = Hearo.find_by(id: params[:hearo_id])
    @review = @hearo.reviews.build
  end

  def create
    @review = Review.new(review_params)
    @review.smyler = current_smyler
    @review.hearo_id = params[:hearo_id]
    if @review.save
      redirect_to hearo_reviews_path(@review.hearo)
    else
      render :new
    end
  end

  private

  def review_params
    params.require(:review).permit(:score, :content)
  end
end

app/controllers/smylers_controller.rb
class SmylersController < ApplicationController
  def show
    @smyler = current_smyler
  end

  def panel
    redirect_home if !smyler_logged_in?
    @smyler = current_smyler
  end

  def new
    redirect_home if smyler_logged_in?
    @smyler = current_smyler
  end

  def create
    if auth
      @smyler = Smyler.find_or_create_by(uid: auth['uid']) do |u|
        u.first_name = auth['info']['name']
        u.email = auth['info']['email']
        u.image = auth['info']['image']
        u.password = "FACEBOOK"  #TODO Find a secure method to use bcrypt in this case
      end
      session[:smyler_id] = @smyler.id
      redirect_to smyler_panel_path
    else
      @smyler = Smyler.new(smyler_params)
      if @smyler.save
        session['smyler_id'] = @smyler.id
        redirect_to smyler_panel_path
      else
        render :new
      end
    end
  end

  def edit
    redirect_home if !smyler_logged_in?
    @smyler = current_smyler
  end

  def update
    @smyler = current_smyler
    if @smyler.update (smyler_params)
      return redirect_to smyler_panel_path
    end
    render :edit
  end

  private
 
  def auth
    request.env['omniauth.auth']
  end

  def smyler_params
    params.require(:smyler).permit(:gender_id, :username, :email, :password, :password_confirmation, :first_name, :last_name, :middle_name, :dob)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def dynamic_route_to_home_string
    if smyler_logged_in?
      smyler_panel_path
    elsif hearo_logged_in?
      hearo_panel_path
    else
      '/'
    end
  end
end

app/helpers/bookings_helper.rb
module BookingsHelper
end

app/helpers/hearos_helper.rb
module HearosHelper
end

app/helpers/meetings_helper.rb
module MeetingsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/smylers_helper.rb
module SmylersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/_navigation_home.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <a class="navbar-brand" href="<%= dynamic_route_to_home_string %>">
    <img src="/assets/smyle-logo-horizontal.png" width="20%" height="20%" class="d-inline-block align-top" alt="">
  </a>

  <% if smyler_logged_in?%>
     <div class="navbar-nav">
      <a class="nav-item nav-link" href="<%= dynamic_route_to_home_string %>">Home</a>
      <a class="nav-item nav-link" href="/meetings">Meetings</a>
      <%= link_to 'Signout', logout_path, class: 'nav-link' %>
    </div>

  <% elsif hearo_logged_in? %>
    <div class="navbar-nav">
      <a class="nav-item nav-link" href="<%= dynamic_route_to_home_string %>">Home</a>
      <a class="nav-item nav-link" href="/meetings">Meetings</a>
      <%= link_to 'Signout', logout_path, class: 'nav-link' %>
    </div>

  <% elsif !logged_in? %>
    <div id="navbarNavDropdown">
      <ul class="navbar-nav">

        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="/welcome/home" id="navbarDropdownMenuLink" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            Smyler Login
          </a>
          <div class="dropdown-menu bg-dark" aria-labelledby="navbarDropdownMenuLink">
            <div class="input-group">
              <%= form_for current_smyler, url: '/sessions', html: {class: "form-inline"} do |f| %>
                  <%= f.text_field :username %>
                  <%= f.password_field :password %>
                  <%= f.submit 'Login' %>
              <% end %>
              <%= link_to "Facebook Login", '/auth/facebook' %>
            </div>
          </div>
        </li>

        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            Hearo Login
          </a>
          <div class="dropdown-menu bg-dark" aria-labelledby="navbarDropdownMenuLink">
            <div class="input-group">
              <%= form_for current_hearo, url: '/sessions', html: {class: "form-inline"} do |f| %>
                  <%= f.text_field :username %>
                  <%= f.password_field :password %>
                  <%= f.submit 'Login' %>
              <% end %>
            </div>
          </div>
        </li>

      </ul>
    </div>
  <% end %> <!-- ends if logged_in -->

</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Smyle</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/navigation_home' %>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>